version: '3.8'

services:
  # Main application (Flask + WebSocket)
  vanessa-app:
    build: ./backend
    container_name: vanessa-app
    ports:
      - "5000:5000"
      - "6000:6000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
      - BASE_URL=${BASE_URL:-http://localhost:5000}
      - WEBSOCKET_URL=${WEBSOCKET_URL:-ws://localhost:6000}
      - FLASK_DEBUG=false
      - FLASK_USE_RELOADER=false
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vanessa-network

  # ngrok tunnel for Flask HTTP (port 5000)
  ngrok-http:
    image: ngrok/ngrok:latest
    container_name: vanessa-ngrok-http
    command: 
      - "http"
      - "vanessa-app:5000"
      - "--log=stdout"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4540:4040"  # ngrok web interface for HTTP tunnel (using 4540 to avoid Windows port restrictions)
    depends_on:
      - vanessa-app
    restart: unless-stopped
    networks:
      - vanessa-network

  # ngrok tunnel for WebSocket (port 6000)
  ngrok-websocket:
    image: ngrok/ngrok:latest
    container_name: vanessa-ngrok-websocket
    command:
      - "http"
      - "vanessa-app:6000"
      - "--log=stdout"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4541:4040"  # ngrok web interface for WebSocket tunnel (mapped to different host port to avoid conflict)
    depends_on:
      - vanessa-app
    restart: unless-stopped
    networks:
      - vanessa-network

networks:
  vanessa-network:
    driver: bridge

