version: '3.8'

services:
  # Main application (Flask + WebSocket)
  vanessa-app:
    build: ./backend
    container_name: vanessa-app
    ports:
      - "5000:5000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
      - BASE_URL=${BASE_URL:-http://localhost:5000}
      - FLASK_DEBUG=false
      - FLASK_USE_RELOADER=false
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - vanessa-network

  # ngrok tunnel for Flask (HTTP + WebSocket on port 5000)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: vanessa-ngrok
    command: 
      - "http"
      - "vanessa-app:5000"
      - "--log=stdout"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4540:4040"  # ngrok web interface (using 4540 to avoid Windows port restrictions)
    depends_on:
      - vanessa-app
    restart: unless-stopped
    networks:
      - vanessa-network

networks:
  vanessa-network:
    driver: bridge

